//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_LDHai.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Account { get; set; }
        public string Group { get; set; }
        public System.DateTime BirthDay { get; set; }
        public System.DateTime StartDate { get; set; }
    }
}
